### ISSUE TITLE
License for use?

### ISSUE THREAD

**Issue by gryftir** [bjesus/teleporter#1]
Hi,

Are you willing to license this code under some sort of open source license (MIT maybe) or otherwise let me modify/share/license my own version from your code? This doesn't work with my laptop.

**Comment by bjesus** [comment]
Of course. Would GPL 3 work for your usage?

Also, would be happy to know what didn't work on your laptop (and what's your setup like?).

**Comment by bjesus** [comment]
Closed for no response
